import { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Methodology — AI Disclosure | BhaavBrief',
  description: 'How BhaavBrief discloses its AI-generation pipeline, validation process, and corrections policy.',
  alternates: { canonical: 'https://bhaavbrief.in/methodology' },
}

const sectionStyle: React.CSSProperties = { marginBottom: '2.5rem' }
const h2Style: React.CSSProperties = {
  fontFamily: 'var(--font-serif)', fontSize: '1.3rem', fontWeight: 700,
  marginBottom: '0.9rem', paddingBottom: '0.5rem', borderBottom: '0.5px solid #DDDDD0',
}
const pStyle: React.CSSProperties = { fontSize: 14.5, color: '#48483A', lineHeight: 1.75, marginBottom: '0.9rem' }

export default function MethodologyPage() {
  return (
    <div style={{ background: '#FAFAF6', minHeight: '100vh' }}>
      <div style={{ maxWidth: 760, margin: '0 auto', padding: '3rem 1.25rem 5rem' }}>
        <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, letterSpacing: '0.1em', textTransform: 'uppercase', color: '#C8720A', marginBottom: 8 }}>
          Methodology
        </div>
        <h1 style={{ fontFamily: 'var(--font-serif)', fontSize: 'clamp(1.8rem, 4vw, 2.4rem)', fontWeight: 800, lineHeight: 1.15, margin: '0 0 1rem' }}>
          How BhaavBrief is built
        </h1>
        <p style={{ ...pStyle, fontSize: 15.5, maxWidth: 620 }}>
          BhaavBrief briefs are generated by an AI pipeline over verified market data, pass automated
          validation before publishing, and are reviewed before going live. This page states plainly what
          the AI is and isn&apos;t allowed to say, and what happens when something needs to be corrected.
        </p>

        <section style={sectionStyle}>
          <h2 style={h2Style}>AI-generation disclosure</h2>
          <p style={pStyle}>
            Briefs are written by Claude (Anthropic) over verified market data — the model never supplies a
            price, a date, or a statistic from memory; it reasons over data assembled by deterministic code
            under a fixed set of hard rules. It is not the last check on its own output: automated
            validation and a separate review pass run after generation, before anything goes live.
          </p>
          <p style={pStyle}>
            BhaavBrief is not a SEBI-registered investment advisor. Nothing on this site is a buy, sell, or
            hold recommendation — every brief carries this disclaimer, and content that reads as advice
            rather than context is blocked before publication.
          </p>
        </section>

        <section style={sectionStyle} id="corrections">
          <h2 style={h2Style}>Corrections policy</h2>
          <p style={pStyle}>
            An error in a published brief gets fixed, not silently edited. A corrected edition carries a
            visible notice at the top of the page — what changed, and when. Corrections are never removed
            from the historical record.
          </p>
        </section>

        <p style={{ fontSize: 12, color: '#8A8A7A', marginTop: '3rem' }}>
          Questions about a specific number in a brief? <Link href="/about" style={{ color: '#C8720A' }}>About BhaavBrief</Link>.
        </p>
      </div>
    </div>
  )
}
