import { Metadata } from 'next'
import Link from 'next/link'
import fs from 'fs'
import path from 'path'

export const revalidate = 300

export const metadata: Metadata = {
  title: 'Methodology — Data Sources, Definitions & AI Disclosure | BhaavBrief',
  description: 'How BhaavBrief sources prices, computes import parity, validates every brief before publishing, prices options, and discloses its AI-generation pipeline.',
  alternates: { canonical: 'https://bhaavbrief.in/methodology' },
}

interface Claim {
  claim_id: string
  statement_template: string
  values: Record<string, number>
  sample_period: string
  n: number
  source: string
  last_verified: string
}

function loadClaims(): Claim[] {
  try {
    const file = path.join(process.cwd(), 'data/claims.json')
    const raw = JSON.parse(fs.readFileSync(file, 'utf8'))
    return raw.claims ?? []
  } catch {
    return []
  }
}

function instantiate(c: Claim): string {
  return c.statement_template.replace(/\{(\w+)\}/g, (_, k) => String(c.values?.[k] ?? `{${k}}`))
}

const sectionStyle: React.CSSProperties = { marginBottom: '2.5rem' }
const h2Style: React.CSSProperties = {
  fontFamily: 'var(--font-serif)', fontSize: '1.3rem', fontWeight: 700,
  marginBottom: '0.9rem', paddingBottom: '0.5rem', borderBottom: '0.5px solid #DDDDD0',
}
const pStyle: React.CSSProperties = { fontSize: 14.5, color: '#48483A', lineHeight: 1.75, marginBottom: '0.9rem' }
const labelStyle: React.CSSProperties = {
  fontFamily: 'var(--font-mono)', fontSize: 10, letterSpacing: '0.08em',
  textTransform: 'uppercase', color: '#8A8A7A', marginBottom: 4,
}

export default function MethodologyPage() {
  const claims = loadClaims()

  return (
    <div style={{ background: '#FAFAF6', minHeight: '100vh' }}>
      <div style={{ maxWidth: 760, margin: '0 auto', padding: '3rem 1.25rem 5rem' }}>
        <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, letterSpacing: '0.1em', textTransform: 'uppercase', color: '#C8720A', marginBottom: 8 }}>
          Methodology
        </div>
        <h1 style={{ fontFamily: 'var(--font-serif)', fontSize: 'clamp(1.8rem, 4vw, 2.4rem)', fontWeight: 800, lineHeight: 1.15, margin: '0 0 1rem' }}>
          How BhaavBrief is built
        </h1>
        <p style={{ ...pStyle, fontSize: 15.5, maxWidth: 620 }}>
          BhaavBrief briefs are generated by an AI pipeline over verified market data, pass automated
          validation gates before publishing, and are reviewed before going live. This page states plainly
          what data feeds the pipeline, how each number is computed, what checks run before anything
          publishes, and what the AI is and isn&apos;t allowed to say. Honesty here is a differentiator, not
          a liability — this page exists because it should have from day one, not because a defect audit
          asked for it.
        </p>

        <section style={sectionStyle}>
          <h2 style={h2Style}>Data sources</h2>
          <p style={pStyle}>
            <strong>MCX prices</strong> — Zerodha Kite Connect, live quotes and historical daily candles,
            refreshed via <code>scripts/fetch-snapshot.mjs</code> on the same cadence as the intelligence
            engine (roughly every 15–30 minutes during market hours, plus a dedicated fetch immediately
            before every brief is generated).
          </p>
          <p style={pStyle}>
            <strong>Global reference prices</strong> — COMEX gold/silver, WTI crude, COMEX copper, Henry
            Hub natural gas, fetched from Yahoo Finance with Alpha Vantage / Stooq / Twelve Data as
            fallbacks if the primary feed is unavailable. A stale feed is carried forward with an explicit
            <code>stale: true</code> flag rather than silently dropped or replaced with an invented number.
          </p>
          <p style={pStyle}>
            <strong>USD/INR</strong> — live FX rate, part of the same snapshot pull as the commodity prices,
            never a hardcoded fallback (an April/May 2026 constant was previously found in old cached
            content; the live pipeline has never had one — see the correction note on affected editions).
          </p>
          <p style={pStyle}>
            <strong>Event calendar</strong> — EIA, API, Baker Hughes, CFTC, and other scheduled release
            dates from <code>data/event-map.json</code>. Historical impact statistics for these events (see
            Claims Ledger below) are computed from real Kite historical candles, not estimated.
          </p>
          <p style={pStyle}>
            <strong>Options chain</strong> — live Kite quotes (LTP, bid/ask depth, OI, volume) for MCX
            options, priced through a Black-76 model (options on futures, not spot — see below).
          </p>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>Import parity &amp; the Price Bridge</h2>
          <p style={pStyle}>
            The Price Bridge on each brief and the <code>/markets</code> page reconciles{' '}
            <em>Global price × USD/INR × (1 + duty/GST wedge) = MCX price</em>. The wedge is not a fixed
            assumption — it&apos;s back-computed daily as{' '}
            <code>(MCX price − import parity) / import parity</code>, where import parity itself is the
            global price converted to INR at the unit MCX actually trades (per 10g for gold, per kg for
            silver). Gold and silver import parity is computed by{' '}
            <code>scripts/fetch-snapshot.mjs</code> on every snapshot fetch.
          </p>
          <p style={pStyle}>
            Gold and silver carry a broadly similar duty/GST structure, so their computed wedges should
            track each other within a few points day to day. A cross-check compares the two spreads and
            writes a warning to the snapshot if they diverge beyond 2 percentage points — this is currently
            non-blocking (surfaced, not enforced) while the root cause of an ongoing divergence is still
            being diagnosed; see the brief&apos;s own footer for the current gap when one exists.
          </p>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>Options model</h2>
          <p style={pStyle}>
            MCX commodity options are options <em>on futures</em>, not on spot — priced with Black-76, not
            Black-Scholes. Implied volatility is solved via Newton-Raphson against the live futures price,
            strike, time to expiry, and a risk-free rate (currently a disclosed constant, dated on the chain
            page footer; automated daily-rate sourcing is planned but not yet live).
          </p>
          <p style={pStyle}>
            Before any quote is solved for IV, it passes a no-arbitrage bounds check (a price outside the
            theoretically possible range for its strike is never solved — it renders as unavailable, not as
            a clamped extreme) and a liquidity/spread classification: <strong>LIVE</strong> (traded today,
            tight bid-ask spread), <strong>STALE</strong> (has some open interest or a quote, but not both
            today), or <strong>JUNK</strong> (no real market — zero OI and volume, or a spread too wide to
            be a real price). The chain view shows LIVE and STALE strikes by default; JUNK strikes are
            hidden behind a &quot;show all&quot; toggle with a warning, never presented as clean data.
          </p>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>Claims ledger</h2>
          <p style={pStyle}>
            Every historical or statistical claim a brief makes (&quot;X has historically moved Y%&quot;)
            must come from this ledger, cited near-verbatim — the generation prompt is constrained to it,
            and a post-generation check blocks publication if a brief states a historical percentage that
            isn&apos;t backed by an entry here. If no ledger entry fits the day&apos;s narrative, the brief
            writes qualitatively instead of inventing a number.
          </p>
          <p style={pStyle}>
            The ledger currently covers <strong>scheduled economic-data-release impact</strong> only — how
            much a commodity has historically moved in the session following a recurring report (EIA
            storage, API inventories, Baker Hughes rig count, CFTC positioning). It deliberately does{' '}
            <strong>not</strong> cover geopolitical reaction patterns (ceasefire timing, &quot;self-limiting&quot;
            price thresholds, rupee-lag assumptions) — there is no verified dataset behind those yet, and a
            plausible-sounding invented number is worse than none. If you have a real backtest for one of
            those patterns, it can be added as a new, sourced entry; it will not be guessed at.
          </p>
          {claims.length === 0 ? (
            <p style={{ ...pStyle, fontStyle: 'italic' }}>
              The ledger is currently empty or unavailable — in that state the brief generator cannot make
              any specific historical-percentage claim at all, which is the correct, conservative default.
            </p>
          ) : (
            <div style={{ border: '0.5px solid #DDDDD0', borderRadius: 4, overflow: 'hidden' }}>
              {claims.map((c) => (
                <div key={c.claim_id} style={{ padding: '0.9rem 1rem', borderBottom: '0.5px solid #DDDDD0', background: '#F3F2EC' }}>
                  <div style={labelStyle}>{c.claim_id}</div>
                  <div style={{ fontSize: 13.5, color: '#18180F', lineHeight: 1.6, marginBottom: 6 }}>{instantiate(c)}</div>
                  <div style={{ fontSize: 11, color: '#8A8A7A' }}>
                    n={c.n} · {c.sample_period} · verified {c.last_verified.slice(0, 10)}
                  </div>
                </div>
              ))}
            </div>
          )}
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>Content tiers</h2>
          <p style={pStyle}>
            <strong>Daily Brief</strong> — the flagship, full editorial standard on this page: verified data,
            the claims ledger constraint, the full publication gate. <strong>Flash</strong> — intraday
            updates, reserved for genuinely market-moving developments (a margin hike, a supply disruption,
            a policy decision) — not a rewrite of a city-wise rate table or other aggregator filler; that
            kind of low-materiality flash content is being phased out as a content tier. <strong>Learn</strong>{' '}
            — evergreen educational guides, not tied to a specific trading day and not claiming any
            time-sensitive market view.
          </p>
        </section>

        <section style={sectionStyle} id="corrections">
          <h2 style={h2Style}>Corrections policy</h2>
          <p style={pStyle}>
            An error in a published brief gets fixed, not silently edited. A corrected edition carries a
            visible notice at the top of the page — what changed, and when — and the frontmatter records
            <code>corrected</code>, <code>correctedAt</code>, and a <code>correctionNote</code>. Corrections
            are never removed from the historical record.
          </p>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>Publication gate</h2>
          <p style={pStyle}>
            Nothing publishes without passing an automated gate (<code>scripts/validate-brief.mjs</code>) —
            data integrity checks (FX sanity, price staleness, Price Bridge reconciliation, no negative
            prices, unconfirmed large moves), content integrity checks (temporal/weekday consistency, the
            claims ledger constraint above, edition numbering, required section structure, SEBI-compliance
            language), and one independent AI review pass that checks the brief for internal
            self-contradictions the deterministic checks can&apos;t catch. A failure blocks publication;
            an infrastructure failure in the gate itself (as opposed to a legitimate content rejection)
            alerts a human rather than failing silently.
          </p>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>AI-generation disclosure</h2>
          <p style={pStyle}>
            Briefs are written by Claude (Anthropic) over the verified data described above — the model
            never supplies a price, a date, or a statistic from memory; it reasons over a payload assembled
            by deterministic code and is constrained by the hard rules above. It is not the last check on
            its own output: the publication gate and a separate review pass run after generation, before
            anything goes live.
          </p>
          <p style={pStyle}>
            BhaavBrief is not a SEBI-registered investment advisor. Nothing on this site is a buy, sell, or
            hold recommendation — every brief carries this disclaimer, and the compliance checks above
            block language that reads as advice rather than context.
          </p>
        </section>

        <p style={{ fontSize: 12, color: '#8A8A7A', marginTop: '3rem' }}>
          Questions about a specific number in a brief? <Link href="/about" style={{ color: '#C8720A' }}>About BhaavBrief</Link>.
        </p>
      </div>
    </div>
  )
}
